"""
The StartPad design system, encoded.

Everything here is traceable to the 2026 brand presentation. Where the presentation
states a rule, the rule is quoted in a comment beside the value it produces, so a
future change is argued against the source rather than against taste.

Colour architecture (ch. 03)
----------------------------
    Lime  #CBF24A   ground, 44%   "At 1.29:1 against white it cannot carry type,
                                   so it is used as ground and never as ink."
    White           working surface, 30%
    Ultraviolet  #3418E0  contrast, 18%   carries white type at 8.9:1
    Ink   #0B0E14   8%

Both measured contrasts reproduce the presentation's figures exactly: lime 1.29:1 and
ultraviolet 8.92:1 against white.

Chart colour
------------
These documents are print. There is one surface — paper — so there is one mode, and
no dark-mode ramp is defined. Every palette below was checked with a validator rather
than chosen by eye; the recorded results are in CHART_PALETTE_CHECKS.
"""

# ---------------------------------------------------------------- core palette

LIME = "#CBF24A"          # ground only, never ink, never lime on lime
ULTRAVIOLET = "#3418E0"   # the surface for anything read at length
INK = "#0B0E14"
WHITE = "#FFFFFF"

# Ink, stepped for hierarchy. Every step is ink desaturated toward the page, so the
# page never carries a grey that came from outside the system.
INK_SECONDARY = "#3A4050"
INK_MUTED = "#6B7285"
INK_FAINT = "#9AA0AF"
HAIRLINE = "#E2E4EA"
WASH = "#F5F6F8"          # the one tinted paper, for worksheet fields and tables

# ------------------------------------------------- the fifteen-mission spectrum
#
# "Ultraviolet to lime through azure, cyan and spring — enough hue travelled that any
#  two adjacent missions are visibly different. Position on the sweep is the meaning."
#
# Generated by interpolating OKLCH from ultraviolet (L .438 C .266 H 272.6) to lime
# (L .904 C .192 H 121.8) across fifteen stops. The arc passes through azure at
# stop 4, cyan at stop 7 and spring at stop 11, which is the sweep the presentation
# describes — the hues were not chosen, they fell out of the two endpoints.

MISSION_SPECTRUM = [
    "#3418E0", "#003EE9", "#005AEE", "#0071ED", "#0087E8",
    "#009AE0", "#00ABD4", "#00BAC6", "#00C8B6", "#00D3A4",
    "#00DC91", "#00E47E", "#6CEA6B", "#A1EE58", "#CBF24A",
]

# Contrast against white falls below 3:1 from stop 6 onward and below 2:1 from stop
# 10. The ribbon that carries this sweep is an identity device, always labelled, and
# never the sole carrier of a value.
SPECTRUM_SAFE_ON_WHITE = 5   # stops 1-5 clear 3:1 unaided

# --------------------------------------------------------------- chart palettes

# Categorical — identity, three slots, fixed order, never cycled. Sampled from the
# brand arc and then re-stepped downward in lightness until every slot cleared 3:1
# on white without relief.
CHART_CATEGORICAL = ["#3418E0", "#0087E8", "#00996B"]

# Ordinal / sequential — magnitude and stage order. One hue (ultraviolet, H 272.6),
# monotone lightness. The mission spectrum is NOT used for generic magnitude: it is a
# multi-hue sweep and its meaning is mission position, not "more".
CHART_ORDINAL = ["#3600F0", "#4338FF", "#5869FF", "#758CFF", "#94AAFF"]

CHART_EMPHASIS = "#3418E0"    # the one series that is the point
CHART_RECEDE = "#C4C8D2"      # everything that is context
CHART_GRID = "#E7E9EF"        # hairline, solid, recessive
CHART_SURFACE = WHITE

# Recorded so the numbers are arguable rather than asserted. Produced by the
# data-visualisation validator: OKLab ΔE ×100, Machado-Oliveira-Fernandes 2009 at
# severity 1.0, all-pairs.
CHART_PALETTE_CHECKS = {
    "categorical": {
        "lightness_band": "PASS — all 3 inside L 0.43-0.77",
        "chroma_floor": "PASS — all 3 >= 0.10",
        "cvd_separation": "PASS — worst all-pairs #0087E8/#3418E0 dE 14.7 deutan",
        "normal_vision_floor": "PASS — worst all-pairs dE 21.3, floor 15",
        "contrast_vs_surface": "PASS — all 3 >= 3:1 on white",
    },
    # Figures generate their ordinal steps at even lightness along this hue rather
    # than snapping to the five documented values, so that n items always get n
    # distinct steps. Checked at every length the library actually uses.
    "ordinal (n = 3, 4, 5 and 6)": {
        "lightness_monotone": "PASS at every n",
        "adjacent_delta_L": "PASS — all gaps >= 0.06 up to n = 6",
        "light_end_contrast": "PASS — #97ABFF at 2.19:1, floor 2.0",
        "single_hue": "PASS — hue spread 0-1 degree",
        "ceiling": "n = 6. At seven steps the adjacent lightness gap falls under "
                   "0.06 and two neighbours stop being distinguishable.",
    },
}

# ------------------------------------------------------------------ typography
#
# "Satoshi. A geometric grotesque with a high x-height and closed apertures."
# Satoshi is Fontshare-distributed and unavailable to this build, so the embedded
# face is Plus Jakarta Sans, matched on those two properties. Satoshi is named first
# in the stack, so a machine that has it uses it.

SATOSHI_FILE = "brand/fonts/PlusJakartaSans-Variable.woff2"
FONT_STACK = "'Satoshi', 'StartPad Sans', 'Liberation Sans', sans-serif"

# "One idea only. LABEL locates the reader and never explains. STATEMENT names the
#  requirement. HEADLINE. BODY carries the reasoning."
TYPE_SCALE = {
    "label": "8.5pt",
    "statement": "25pt",
    "h1": "23pt",
    "h2": "14.5pt",
    "h3": "11pt",
    "body": "10.2pt",
    "small": "9pt",
    "caption": "8.2pt",
    "hero": "58pt",
}

# ------------------------------------------------------------------ voice rules
#
# Kept next to the design tokens because they are enforced the same way: by being
# written down. From ch. 05, SAY / NEVER SAY.

NEVER_SAY = [
    "You've got this",
    "Your journey starts here",
    "Your idea is safe with us",
    "We built a founder",
    "unlock", "empower", "revolutionary", "game-changing",
]

LOGO_INK = "brand/logo/startpad_horizontal_ink.png"
LOGO_WHITE = "brand/logo/startpad_horizontal_white.png"
LOGO_STACKED_WHITE = "brand/logo/startpad_stacked_white.png"

URL = "startpad.me"
