"""
Startpad — the 15 missions, and which tools belong inside each one.

Mapping rules used throughout:

  CORE       The founder cannot produce a good answer to this mission's questions
             without it. Surface it in the mission workspace, pre-opened.
  SUPPORTING Recommended. Sharpens the answer or de-risks it. Show in a
             "recommended tools" rail the founder can open with one click.
  STRETCH    Optional / for the ambitious founder or a second pass. Show under
             "go deeper".

`feeds` names the mission question (Q1..Qn from the mission spec) that the tool's
output should populate, so the platform can pre-fill the answer field from the tool.
"""

MISSIONS = [
    dict(id=1, title="Problem Analysis", category="Discovery", phase="Discovery",
         points=100, time="2-3 hours",
         summary="Understand problems, key facts, and research insights",
         questions=[
             "What area/industry are you interested in?",
             "Describe a specific problem you've observed",
             "Who is affected by this problem?",
             "What solutions currently exist?",
             "What are the limitations of current solutions?",
         ]),
    dict(id=2, title="Problem Definition", category="Discovery", phase="Discovery",
         points=100, time="1-2 hours",
         summary="Identify users and their specific problems",
         questions=[
             "Who is your primary user?",
             "Describe their key characteristics",
             "What specific problem do they face?",
             "When/where does this problem occur?",
             "How often does this problem occur?",
         ]),
    dict(id=3, title="Importance/Frequency Matrix", category="Analysis", phase="Analysis",
         points=150, time="1 hour",
         summary="Prioritize problems based on impact and frequency",
         questions=[
             "Problem 1", "Importance (1-10)", "Frequency (1-10)",
             "Problem 2", "Importance (1-10)", "Frequency (1-10)",
             "Which problem will you focus on?",
         ]),
    dict(id=4, title="Problem Statements", category="Analysis", phase="Analysis",
         points=150, time="2 hours",
         summary="Create clear, actionable problem statements",
         questions=[
             "Write your main problem statement",
             "Who specifically faces this problem?",
             "What is the impact of this problem?",
             "How will you measure success?",
         ]),
    dict(id=5, title="Idea Selection", category="Ideation", phase="Ideation",
         points=200, time="1-2 hours",
         summary="Use value/impact matrix to select best ideas",
         questions=[
             "Solution Idea 1", "Value Score (1-10)", "Impact Score (1-10)",
             "Solution Idea 2", "Value Score (1-10)", "Impact Score (1-10)",
             "Which idea will you pursue?", "Why did you select this idea?",
         ]),
    dict(id=6, title="Idea Description", category="Ideation", phase="Ideation",
         points=200, time="2-3 hours",
         summary="Develop problem-solution canvas",
         questions=[
             "What is your value proposition?",
             "List 3-5 key features",
             "What benefits will users get?",
             "How is this different from existing solutions?",
             "What assumptions are you making?",
         ]),
    dict(id=7, title="Solution Hypothesis Test", category="Validation", phase="Validation",
         points=250, time="3-5 hours",
         summary="Validate your solution hypothesis",
         questions=[
             "What is your main hypothesis?",
             "How will you test this hypothesis?",
             "What would prove your hypothesis correct?",
             "What were your test results?",
             "What did you learn?",
         ]),
    dict(id=8, title="Business Model Canvas", category="Business Model", phase="Business Model",
         points=300, time="3-4 hours",
         summary="Develop comprehensive business model",
         questions=[
             "Value Propositions", "Customer Segments", "Channels",
             "Customer Relationships", "Revenue Streams", "Key Resources",
             "Key Activities", "Key Partnerships", "Cost Structure",
         ]),
    dict(id=9, title="Build Prototype", category="Development", phase="Development",
         points=300, time="5-10 hours",
         summary="Create prototype or Figma design",
         questions=[
             "What type of prototype did you create?",
             "What key features does it include?",
             "What user flows did you design?",
             "What tools did you use?",
             "Link to prototype (if applicable)",
             "What are your next steps?",
         ]),
    dict(id=10, title="Solution Hypothesis Test (Prototype)", category="Validation",
         phase="Validation", points=300, time="3-5 hours",
         summary="Further validation with prototype",
         questions=[
             "How many people tested your prototype?",
             "How did you conduct the tests?",
             "What were the key findings?",
             "What feedback did users provide?",
             "What improvements will you make?",
         ]),
    dict(id=11, title="Service Selection", category="Strategy", phase="Strategy",
         points=300, time="2-3 hours",
         summary="Define go-to-market strategy",
         questions=[
             "Who is your target market?",
             "What marketing channels will you use?",
             "What is your pricing strategy?",
             "Describe your sales process",
             "What is your launch plan?",
         ]),
    dict(id=12, title="Market Validation", category="Validation", phase="Validation",
         points=350, time="4-6 hours",
         summary="Test market readiness and demand",
         questions=[
             "How did you validate the market?",
             "What indicators of demand did you find?",
             "What did you learn about competitors?",
             "How did the market respond to your pricing?",
             "What is your estimated market size?",
         ]),
    dict(id=13, title="Build MVP", category="Development", phase="Development",
         points=400, time="20-40 hours",
         summary="Develop minimum viable product",
         questions=[
             "What features did you include in your MVP?",
             "What technology stack did you use?",
             "How long did development take?",
             "What challenges did you face?",
             "Link to your MVP (if applicable)",
             "Is your MVP ready for launch?",
         ]),
    dict(id=14, title="Product-Market Fit Test", category="Validation", phase="Validation",
         points=450, time="5-10 hours",
         summary="Validate product-market fit",
         questions=[
             "How did your MVP launch go?",
             "What user metrics did you achieve?",
             "What feedback did users provide?",
             "What is your user retention rate?",
             "Rate your product-market fit (1-10)",
             "What improvements will you make?",
         ]),
    dict(id=15, title="Go to Market", category="Launch", phase="Launch",
         points=500, time="10-20 hours",
         summary="Execute launch strategy",
         questions=[
             "Describe your launch strategy",
             "What marketing campaigns did you run?",
             "What were your launch results?",
             "How many users did you acquire?",
             "What revenue did you generate?",
             "What are your next steps for growth?",
         ]),
]

MISSION_BY_ID = {m["id"]: m for m in MISSIONS}

# mission_id -> {"core"|"supporting"|"stretch": [(tool_name, why_this_tool, feeds_question)]}
MAPPING = {
    1: {
        "core": [
            ("Market Research Brief",
             "Frames the industry scan before any opinion forms — market, trends, players, sources.",
             "Q1 What area/industry are you interested in?"),
            ("Problem Statement",
             "Forces the observed problem into a precise sentence and scores its frequency × intensity, so 'a problem I noticed' becomes a measured one.",
             "Q2 Describe a specific problem you've observed"),
            ("Jobs-to-be-Done",
             "Captures what the person is actually trying to get done — stops the founder describing a feature instead of a problem.",
             "Q2 / Q3"),
            ("Competitor Feature Coverage",
             "The white-space matrix: list every existing solution and what it does/doesn't cover. Directly answers Q4 and Q5.",
             "Q4 What solutions currently exist? · Q5 Limitations"),
            ("Interview Script Builder",
             "Mom-Test style script so the first conversations produce facts, not polite encouragement.",
             "Q2 / Q3 (evidence behind the answers)"),
        ],
        "supporting": [
            ("Customer Persona",
             "A first sketch of who is affected — refined properly in Mission 2.",
             "Q3 Who is affected by this problem?"),
            ("Assumptions Tracker",
             "Log every belief you are treating as fact from day one; this list drives Missions 7 and 12.",
             "Q5 (what you assume about current solutions)"),
            ("PESTEL Analysis",
             "Macro scan — regulation, economics, tech shifts — that explains why the problem exists now.",
             "Q1"),
        ],
        "stretch": [
            ("Interview Synthesis",
             "If you managed more than 3 conversations, synthesise them instead of quoting the loudest one.",
             "Q2 / Q5"),
            ("SWOT Analysis",
             "Early read on where you could play, if you already have an angle.", "Q1"),
        ],
    },
    2: {
        "core": [
            ("Customer Persona",
             "The mission's whole job: one named, specific user. Feeds Q1 and Q2 line for line.",
             "Q1 Who is your primary user? · Q2 Key characteristics"),
            ("Jobs-to-be-Done",
             "Ties the persona to a concrete job, with the trigger and the current workaround.",
             "Q3 What specific problem do they face?"),
            ("Interview Script Builder",
             "You cannot answer Q4/Q5 from a desk. The script gets context and frequency from real users.",
             "Q4 When/where does it occur? · Q5 How often?"),
            ("Interview Synthesis",
             "Turns 5-10 interviews into the patterns that become the persona's characteristics.",
             "Q2 / Q3"),
            ("Problem Statement",
             "Frequency (1-10) and Intensity (1-10) inputs are literally Q5 and the severity behind Q3.",
             "Q3 / Q5"),
        ],
        "supporting": [
            ("Assumptions Tracker",
             "Every persona attribute you did not hear from a real user is an assumption — log it now.",
             "Q2"),
            ("Survey Sample Size",
             "Tells you how many people you need before 'how often' is a number rather than a guess.",
             "Q5 How often does this problem occur?"),
            ("Market Sizing (TAM/SAM/SOM)",
             "A first count of how many people match this persona.", "Q1"),
        ],
        "stretch": [
            ("Churn by Segment",
             "If you already have users, shows which segment actually has the problem worst.", "Q1"),
        ],
    },
    3: {
        "core": [
            ("Importance / Frequency Matrix",
             "This mission IS the tool. Plot each candidate problem on importance × frequency and read the quadrant.",
             "Q1-Q6 (all problem/importance/frequency pairs)"),
            ("Problem Statement",
             "Its severity score (frequency × intensity) is the numeric input for each problem you plot.",
             "Q2/Q3 and Q5/Q6 scores"),
            ("Idea Scorecard",
             "Weighted scoring for the tie-break when two problems land in the same quadrant.",
             "Q7 Which problem will you focus on?"),
        ],
        "supporting": [
            ("Assumptions Tracker",
             "Ranks the riskiest assumption behind each score, so you know which number is softest.",
             "Q7"),
            ("Interview Synthesis",
             "Sources the scores from evidence rather than founder instinct.", "Q2-Q6"),
            ("Survey Sample Size",
             "If you want the frequency scores to be defensible, this sets the n you need.", "Q3 / Q6"),
        ],
        "stretch": [
            ("Value vs Effort",
             "A second lens: some high-importance problems are unreachable for a team of your size.", "Q7"),
        ],
    },
    4: {
        "core": [
            ("Problem Statement",
             "The mission deliverable in one tool — target user, pain, frequency, intensity, evidence.",
             "Q1 Main problem statement · Q2 Who specifically"),
            ("Customer Persona",
             "Q2 asks 'who specifically'. The persona is the specific answer.",
             "Q2 Who specifically faces this problem?"),
            ("Market Sizing (TAM/SAM/SOM)",
             "Quantifies impact — how many people × how much it costs them.",
             "Q3 What is the impact of this problem?"),
            ("Hypothesis Builder",
             "Turns the statement into a falsifiable claim, which is what Mission 7 will test.",
             "Q1 / Q4"),
            ("North Star Metric",
             "Q4 asks how you'll measure success. This defines the one number, before you build anything.",
             "Q4 How will you measure success?"),
        ],
        "supporting": [
            ("Positioning Statement",
             "The 'For / Who / Unlike' skeleton keeps the problem statement customer-first, not product-first.",
             "Q1"),
            ("Validation Scorecard",
             "Scores how much real evidence sits behind the statement — honest baseline before validation.",
             "Q1"),
            ("KPI Scorecard",
             "Sets target vs actual for the success measure so Q4 has a threshold, not just a metric name.",
             "Q4"),
        ],
        "stretch": [
            ("Vision & Mission",
             "If the problem is one you intend to spend years on, write the long-form version now.", "Q1"),
        ],
    },
    5: {
        "core": [
            ("Value vs Effort",
             "This mission IS the value/impact matrix. Plot every candidate solution and read the quadrant.",
             "Q2/Q3 and Q5/Q6 scores"),
            ("Idea Scorecard",
             "Weighted, multi-criteria scoring — the objective backup for 'why did you select this idea'.",
             "Q7 Which idea · Q8 Why"),
            ("Feature Prioritisation — RICE",
             "Where two ideas score alike, Reach × Impact × Confidence ÷ Effort separates them with numbers.",
             "Q7 / Q8"),
        ],
        "supporting": [
            ("Experiment Backlog — ICE",
             "Sequences the ideas you did NOT pick into a backlog instead of losing them.", "Q7"),
            ("Build vs Buy",
             "Some ideas are cheaper to integrate than to build — changes the effort score materially.",
             "Q3 / Q6 Impact & effort scores"),
            ("Assumptions Tracker",
             "Each idea rests on assumptions; the riskiest one should influence the choice.", "Q8"),
            ("SWOT Analysis",
             "Checks the chosen idea against what your team is actually good at.", "Q8"),
        ],
        "stretch": [
            ("Revenue Model Designer",
             "An idea you cannot charge for is a feature, not a startup — sanity-check monetisation early.",
             "Q8"),
        ],
    },
    6: {
        "core": [
            ("Value Proposition Canvas",
             "The problem-solution canvas this mission asks for: pains/gains on the right, your value map on the left.",
             "Q1 Value proposition · Q3 Benefits"),
            ("Lean Canvas",
             "One page that holds problem, solution, UVP and unfair advantage together — the mission on a page.",
             "Q1 / Q2 / Q4"),
            ("Product Description",
             "Name, core features, benefits, use cases, differentiators — directly answers Q2 and Q3.",
             "Q2 List 3-5 key features · Q3 Benefits"),
            ("Elevator Pitch",
             "Forces the value proposition into 30 seconds. If it doesn't fit, Q1 isn't finished.",
             "Q1 What is your value proposition?"),
            ("Assumptions Tracker",
             "Q5 asks what you're assuming. This tool is the register, ranked by risk.",
             "Q5 What assumptions are you making?"),
        ],
        "supporting": [
            ("Competitor Feature Coverage",
             "Q4 (how is this different) is only credible against a mapped competitive set.",
             "Q4 How is this different from existing solutions?"),
            ("Positioning Statement",
             "'Unlike [alternative], we [differentiator]' is the sentence Q4 wants.", "Q4"),
            ("MVP Scope (MoSCoW)",
             "Turns the 3-5 key features into must / should / could before Mission 9 begins.", "Q2"),
        ],
        "stretch": [
            ("Business Model Canvas",
             "A first pass now makes Mission 8 an edit rather than a blank page.", "Q1"),
            ("Brand Identity",
             "If the value proposition is emotional as much as functional, define the brand basics.", "Q3"),
        ],
    },
    7: {
        "core": [
            ("Hypothesis Builder",
             "Q1 asks for a hypothesis. This tool makes it falsifiable: 'We believe X. We'll know we're right if Y.'",
             "Q1 What is your main hypothesis?"),
            ("Assumptions Tracker",
             "Riskiest-Assumption-Test ranking tells you which hypothesis is worth testing first.", "Q1"),
            ("Interview Script Builder",
             "The most common test at this stage. Designed to avoid leading questions.",
             "Q2 How will you test this hypothesis?"),
            ("Validation Scorecard",
             "Q3 asks what would prove you right — this sets the pass threshold before you see results.",
             "Q3 What would prove your hypothesis correct?"),
            ("Interview Synthesis",
             "Converts raw conversations into the findings Q4 and Q5 ask for.",
             "Q4 Test results · Q5 What did you learn?"),
        ],
        "supporting": [
            ("Demand / Smoke Test",
             "A landing page + traffic proves interest with behaviour, not opinions.", "Q2 / Q4"),
            ("Landing Page Brief",
             "Specs the smoke-test page so the test measures the offer, not bad copy.", "Q2"),
            ("Survey Sample Size",
             "Sets how many responses make the result meaningful rather than anecdotal.", "Q3"),
            ("Waitlist / Pre-order Tracker",
             "The strongest early signal: someone gave you their email or their money.", "Q4"),
        ],
        "stretch": [
            ("A/B Test",
             "If you have enough traffic, test two framings of the value proposition against each other.",
             "Q2 / Q4"),
            ("Willingness-to-Pay Test",
             "Tests price alongside desirability — worth doing now if you can.", "Q4"),
        ],
    },
    8: {
        "core": [
            ("Business Model Canvas",
             "The mission IS this canvas. All 9 blocks map 1:1 onto Q1-Q9.", "Q1-Q9 (all nine blocks)"),
            ("Value Proposition Canvas",
             "Feeds the Value Propositions and Customer Segments blocks with tested detail.",
             "Q1 Value Propositions · Q2 Customer Segments"),
            ("Revenue Model Designer",
             "Q5 Revenue Streams needs a chosen pattern — subscription, transaction, marketplace, licence.",
             "Q5 Revenue Streams"),
            ("Pricing Strategy",
             "A revenue stream without a price is not a business model.", "Q5 Revenue Streams"),
            ("Cost Structure & Budget",
             "Q9 asks for cost structure. This is the real line-item breakdown, not a guess.",
             "Q9 Cost Structure"),
            ("Unit Economics",
             "Proves the model works per customer before it has to work at scale.", "Q5 / Q9"),
        ],
        "supporting": [
            ("Channel CAC Planner",
             "Q3 Channels is only answered when you know what each channel costs.", "Q3 Channels"),
            ("Partnership / BD Pipeline",
             "Turns Q8 Key Partnerships from a wish list into a pipeline with named counterparties.",
             "Q8 Key Partnerships"),
            ("Team Roles & Hiring Plan",
             "Key Resources are mostly people at this stage.", "Q6 Key Resources"),
            ("Break-Even Analysis",
             "Tests whether the price and cost structure you just wrote can ever meet.", "Q5 / Q9"),
            ("Lean Canvas",
             "The lighter alternative if the full BMC is too heavy for a pre-revenue idea.", "Q1-Q9"),
            ("Willingness-to-Pay Test",
             "Grounds the revenue block in what customers said they'd pay.", "Q5"),
        ],
        "stretch": [
            ("Income Statement (P&L)",
             "Turn the canvas into a first monthly P&L — makes the model numeric.", "Q5 / Q9"),
            ("Operating Budget / OpEx",
             "Departmental view of the cost structure.", "Q9"),
            ("Customer Health Score",
             "If your model depends on retention, define what a healthy customer looks like now.", "Q4"),
        ],
    },
    9: {
        "core": [
            ("MVP Scope (MoSCoW)",
             "Decides what the prototype must show and what it explicitly will not — the discipline this mission needs.",
             "Q2 What key features does it include?"),
            ("Product Roadmap",
             "Now / Next / Later sequencing so the prototype is step one of a plan, not a one-off.",
             "Q6 What are your next steps?"),
            ("Value vs Effort",
             "Fast triage of which flows are worth prototyping in the hours you have.", "Q2 / Q3"),
            ("Tech Stack Selector",
             "Q4 asks what tools you used. Weighted decision matrix instead of picking what's familiar.",
             "Q4 What tools did you use?"),
        ],
        "supporting": [
            ("Feature Prioritisation — RICE",
             "Ranks the features inside the must-have set when even those don't all fit.", "Q2"),
            ("Build vs Buy",
             "At prototype stage, most things should be bought or faked, not built.", "Q4"),
            ("Product Description",
             "The one-liner that the prototype's first screen has to communicate.", "Q1"),
            ("Landing Page Brief",
             "If the prototype is a landing page or concierge test, this specs it.", "Q1 / Q3"),
            ("Sprint Velocity / ETA",
             "Sets a realistic finish date for the 5-10 hour budget.", "Q6"),
        ],
        "stretch": [
            ("Interview Script Builder",
             "Write the test script while you build, so Mission 10 starts immediately.", "Q6"),
            ("Risk Register",
             "Technical risks the prototype should be designed to expose early.", "Q6"),
        ],
    },
    10: {
        "core": [
            ("User Testing Synthesis",
             "The mission deliverable: task success, time on task, severity-ranked usability findings.",
             "Q3 Key findings · Q4 User feedback"),
            ("Interview Script Builder",
             "Q2 asks how you conducted the tests — a written protocol is the answer.",
             "Q2 How did you conduct the tests?"),
            ("Hypothesis Builder",
             "Each test session should test a stated belief, not just 'see what they think'.", "Q2 / Q3"),
            ("Validation Scorecard",
             "Turns mixed qualitative feedback into one evidence score you can compare to Mission 7.",
             "Q3 / Q5"),
            ("Survey Sample Size",
             "Q1 asks how many people tested. This says how many were enough.",
             "Q1 How many people tested your prototype?"),
        ],
        "supporting": [
            ("NPS",
             "One comparable number across test rounds.", "Q3"),
            ("Interview Synthesis",
             "For the open-ended half of each session.", "Q4"),
            ("Assumptions Tracker",
             "Mark which assumptions the tests killed, confirmed, or left open.", "Q3 / Q5"),
            ("Feature Adoption",
             "If the prototype is clickable and instrumented, shows which features got touched at all.",
             "Q3"),
            ("Value vs Effort",
             "Prioritises the improvement list Q5 asks for.", "Q5 What improvements will you make?"),
        ],
        "stretch": [
            ("Engagement Score",
             "For interactive prototypes with enough sessions to score.", "Q3"),
            ("Feature Prioritisation — RICE",
             "Ranks the fix list with numbers before Mission 13.", "Q5"),
        ],
    },
    11: {
        "core": [
            ("Go-to-Market Plan",
             "The mission's spine: segment, positioning, channels, messaging, motion, budget.",
             "Q1-Q5 (all)"),
            ("Marketing Strategy",
             "STP + 4Ps — the structured answer to 'who is your target market' and 'which channels'.",
             "Q1 Target market · Q2 Marketing channels"),
            ("Channel CAC Planner",
             "Q2 is only answerable with cost per channel — otherwise it's a list of hopes.",
             "Q2 What marketing channels will you use?"),
            ("Pricing Strategy",
             "Q3 asks for a pricing strategy — cost-plus vs value-based, with the reasoning.",
             "Q3 What is your pricing strategy?"),
            ("Pricing Tiering / ARPU",
             "Turns one price into a Good-Better-Best structure and an expected ARPU.", "Q3"),
            ("Sales Strategy",
             "Q4 asks you to describe the sales process — motion, stages, tactics, quota.",
             "Q4 Describe your sales process"),
        ],
        "supporting": [
            ("Positioning Statement",
             "Every channel message inherits from this sentence.", "Q1"),
            ("Marketing / Sales Funnel",
             "Models the conversion path the channels are supposed to feed.", "Q2 / Q4"),
            ("Sales Velocity",
             "Deals × value × win rate ÷ cycle length — makes the sales process a forecast.", "Q4"),
            ("Sales Capacity",
             "Tells you how many deals the current team can actually carry.", "Q4"),
            ("Brand Identity",
             "The voice and look every launch asset will use.", "Q2"),
            ("Content Cadence",
             "The publishing calendar behind an owned-channel strategy.", "Q2"),
            ("Launch Checklist",
             "Q5 asks for a launch plan — this is the plan in checklist form.",
             "Q5 What is your launch plan?"),
            ("Marketing Materials",
             "The asset list the launch plan depends on.", "Q5"),
        ],
        "stretch": [
            ("Market Expansion Priority",
             "If more than one geography or segment is in play, rank them.", "Q1"),
            ("Partnership / BD Pipeline",
             "Channel partners are a go-to-market motion in their own right in MENA.", "Q2"),
            ("Referral / Viral Loop",
             "Designs acquisition that doesn't cost per head.", "Q2"),
        ],
    },
    12: {
        "core": [
            ("Market Sizing (TAM/SAM/SOM)",
             "Q5 asks for estimated market size — bottom-up, with your math shown.",
             "Q5 What is your estimated market size?"),
            ("Demand / Smoke Test",
             "Q1/Q2 want real demand indicators: traffic, sign-ups, conversion — behaviour, not opinion.",
             "Q1 How did you validate? · Q2 Indicators of demand"),
            ("Willingness-to-Pay Test",
             "Van Westendorp gives Q4 an evidence-based answer instead of an anecdote.",
             "Q4 How did the market respond to your pricing?"),
            ("Competitor Feature Coverage",
             "Q3 asks what you learned about competitors — the feature-gap matrix is the artefact.",
             "Q3 What did you learn about competitors?"),
            ("Waitlist / Pre-order Tracker",
             "Converts interest into a committed number you can quote to investors.", "Q2"),
            ("Validation Scorecard",
             "One evidence-based score across everything you ran in this mission.", "Q1"),
        ],
        "supporting": [
            ("Porter's Five Forces",
             "Deepens Q3 from 'who else exists' to 'is this industry structurally winnable'.", "Q3"),
            ("Survey Sample Size",
             "Makes the demand numbers defensible.", "Q1 / Q2"),
            ("PESTEL Analysis",
             "Regulatory and economic conditions that decide whether the market is ready now.", "Q1"),
            ("Market Research Brief",
             "Sources and trend data behind the market size number.", "Q5"),
            ("CAC Calculator",
             "Cost per acquired customer from the smoke test — the first real CAC you'll have.", "Q2"),
            ("Paid Ads Performance",
             "If you drove test traffic with paid ads, this reads CTR/CPC/CPA.", "Q1 / Q2"),
        ],
        "stretch": [
            ("Market Expansion Priority",
             "Ranks which sub-market to attack first.", "Q5"),
            ("New Market Entry Scorecard",
             "For cross-border MENA expansion decisions.", "Q5"),
            ("Landing Page Brief",
             "If the smoke test needs a second, sharper page.", "Q1"),
        ],
    },
    13: {
        "core": [
            ("MVP Scope (MoSCoW)",
             "Q1 asks what features you included. Must/Should/Could is the discipline that keeps 20-40 hours from becoming 200.",
             "Q1 What features did you include in your MVP?"),
            ("Product Roadmap",
             "Now/Next/Later — what ships in the MVP and what is explicitly deferred.", "Q1 / Q6"),
            ("Tech Stack Selector",
             "Q2 asks for your stack. A weighted matrix beats defaulting to what you know.",
             "Q2 What technology stack did you use?"),
            ("Sprint Velocity / ETA",
             "Q3 asks how long development took — plan it, then compare to actual.",
             "Q3 How long did development take?"),
            ("Feature Prioritisation — RICE",
             "Ranks inside the must-have set when the build is still too big.", "Q1"),
            ("Burn Rate & Runway",
             "A 20-40 hour build has a cash cost. This says whether you can afford to finish.",
             "Q4 What challenges did you face?"),
        ],
        "supporting": [
            ("Build vs Buy",
             "Auth, payments, notifications — buy them. TCO comparison in one place.", "Q2"),
            ("Risk Register",
             "Q4 asks about challenges. Ranked risks turn surprises into managed items.", "Q4"),
            ("North Star Metric",
             "Instrument the MVP for this metric before launch or Mission 14 has no data.",
             "Q6 Is your MVP ready for launch?"),
            ("AARRR Funnel",
             "Defines the events to log at build time — acquisition through revenue.", "Q6"),
            ("Cost Structure & Budget",
             "The real cost of building and running the MVP.", "Q4"),
            ("Team Roles & Hiring Plan",
             "If you can't build it alone, this is who you need and when.", "Q4"),
            ("Legal Checklist",
             "Terms, privacy policy and data handling must exist before real users touch the MVP.",
             "Q6"),
        ],
        "stretch": [
            ("Hiring Cost Model",
             "Fully-loaded cost of the first engineer or contractor.", "Q4"),
            ("Rolling Cash Forecast",
             "13-week cash view across the build period.", "Q4"),
            ("IP Strategy",
             "Assign IP to the company before contractors touch the codebase.", "Q6"),
            ("Team Structure & Equity",
             "If a co-founder or early employee joins for the build, agree equity before, not after.",
             "Q4"),
        ],
    },
    14: {
        "core": [
            ("Cohort Retention",
             "The single most honest PMF signal: do cohorts stay? Feeds Q4 directly.",
             "Q4 What is your user retention rate?"),
            ("Retention Curve",
             "A curve that flattens is product-market fit. A curve that hits zero is not.", "Q4 / Q5"),
            ("NPS",
             "Structured user sentiment for Q3, comparable month to month.",
             "Q3 What feedback did users provide?"),
            ("North Star Metric",
             "Q2 asks what metrics you achieved — the North Star is the headline one.",
             "Q2 What user metrics did you achieve?"),
            ("AARRR Funnel",
             "Q1/Q2 need the whole funnel: acquisition, activation, retention, referral, revenue.",
             "Q1 How did your MVP launch go? · Q2"),
            ("Engagement Score",
             "Distinguishes sign-ups from actual usage — the difference PMF lives in.", "Q2"),
            ("Validation Scorecard",
             "Q5 asks you to rate PMF 1-10. This makes that rating evidence-based rather than a mood.",
             "Q5 Rate your product-market fit (1-10)"),
        ],
        "supporting": [
            ("Churn & Retention",
             "The inverse view, and the one investors will ask about.", "Q4"),
            ("Churn by Segment",
             "Shows PMF is often real for one segment and absent for another — the Superhuman insight.",
             "Q4 / Q6"),
            ("DAU/MAU Stickiness",
             "Frequency of use, for products that should be habitual.", "Q2"),
            ("Growth Accounting",
             "Splits net growth into new / resurrected / churned so a flat number stops hiding trouble.",
             "Q2"),
            ("Feature Adoption",
             "Which features the retained users actually use — the roadmap input for Q6.", "Q6"),
            ("Customer Health Score",
             "Predicts who is about to churn while you can still act.", "Q4"),
            ("LTV Calculator",
             "Retention has now made LTV computable rather than theoretical.", "Q2"),
            ("CAC Calculator",
             "Real acquisition cost from the launch.", "Q2"),
            ("LTV:CAC & Payback",
             "The ratio that says whether growth is worth funding.", "Q2"),
            ("User Testing Synthesis",
             "Qualitative depth behind the numbers.", "Q3"),
        ],
        "stretch": [
            ("Survey Sample Size",
             "The Sean Ellis 40% survey needs a defensible n.", "Q5"),
            ("Interview Synthesis",
             "Interview the users who would be 'very disappointed' — they define your ICP.", "Q3 / Q6"),
            ("Feature Prioritisation — RICE",
             "Ranks the Q6 improvement list.", "Q6 What improvements will you make?"),
            ("Expansion & NRR",
             "If you have paying accounts, expansion revenue is the strongest PMF proof there is.",
             "Q2"),
        ],
    },
    15: {
        "core": [
            ("Launch Checklist",
             "Q1 asks you to describe the launch strategy — this is the executable version.",
             "Q1 Describe your launch strategy"),
            ("Launch Budget",
             "What the launch costs and what CPA it implies.", "Q2 What campaigns did you run?"),
            ("Marketing / Sales Funnel",
             "Models and then measures the funnel the campaigns feed.",
             "Q3 Launch results · Q4 Users acquired"),
            ("Channel ROI / ROAS",
             "Q3 asks for results. ROAS per channel is the answer that tells you what to do next.",
             "Q3 / Q6"),
            ("Experiment Tracker",
             "Launch is a sequence of experiments; this logs each one and what it taught.", "Q2 / Q3"),
            ("MRR / ARR Tracker",
             "Q5 asks what revenue you generated — the recurring view, not just cash in.",
             "Q5 What revenue did you generate?"),
            ("Marketing Materials",
             "The asset set the launch needs, planned rather than improvised.", "Q2"),
        ],
        "supporting": [
            ("PR Plan",
             "Story angle, target media, timeline — the earned-media half of the launch.", "Q2"),
            ("Launch Event",
             "For MENA ecosystems, a launch moment with partners often outperforms paid.", "Q2"),
            ("Paid Ads Performance",
             "CTR / CPC / CPA per campaign.", "Q2 / Q3"),
            ("Conversion Rate Optimisation",
             "Turns the same traffic into more users — the cheapest growth in the first month.",
             "Q4 How many users did you acquire?"),
            ("A/B Test",
             "Tests the launch messaging with real traffic.", "Q2"),
            ("Referral / Viral Loop",
             "Q6 asks about growth next steps; K-factor is the compounding one.",
             "Q6 Next steps for growth"),
            ("Experiment Backlog — ICE",
             "Prioritises what to try in the weeks after launch day.", "Q6"),
            ("SaaS Metrics Dashboard",
             "One board with the numbers an investor or mentor will ask for.", "Q3 / Q5"),
            ("KPI Tracker — Actual vs Projected",
             "Launch is the first month where actuals exist to compare against the plan.", "Q3"),
            ("Content Cadence",
             "Sustains attention past launch week.", "Q6"),
            ("Brand Identity",
             "Keeps every launch asset consistent.", "Q2"),
        ],
        "stretch": [
            ("Growth Rate & CAGR", "Quantifies momentum for the first investor update.", "Q6"),
            ("KPI Scorecard", "Target vs actual across the launch KPIs.", "Q3"),
            ("Rule of 40", "Once revenue exists, the growth-vs-burn balance check.", "Q6"),
            ("Magic Number", "Sales efficiency, if you have a sales motion.", "Q6"),
            ("Scaling Readiness Scorecard", "Decides whether to scale or keep iterating.", "Q6"),
            ("Revenue per Employee", "Productivity check before you hire on launch optimism.", "Q6"),
        ],
    },
}

# -------------------------------------------------------------------------
# Tools with no natural home inside the 15 missions.
# These are the "Founder Toolkit" — always available from the tool library,
# surfaced by trigger rather than by mission, plus a proposed Mission 16.
# -------------------------------------------------------------------------
ALWAYS_AVAILABLE = {
    "Fundraising track (proposed Mission 16 — 'Raise Your Round')": [
        ("Pitch Narrative", "The 7-beat story before any slide is designed."),
        ("Pitch Deck Builder (12 slides)", "The deck itself — companion Word template."),
        ("Investor One-Pager", "The leave-behind / cold-send page."),
        ("Fundability Scorecard", "Honest investor-readiness score before you start pitching."),
        ("Funding Ask", "How much to raise, backed by the runway math."),
        ("Use of Funds", "Where the money goes — slide 12's supporting detail."),
        ("Fundraising Pipeline", "Investor CRM; a raise is a sales process."),
        ("Data Room Checklist", "What diligence will ask for, assembled in advance."),
        ("Investor Update Delta", "Monthly update — the habit that makes the next round easier."),
        ("Cap Table — dynamic, multi-round", "Who owns what, at every stage."),
        ("SAFE Conversion", "What the SAFE becomes at the priced round."),
        ("Quick Dilution What-If", "Napkin math before a conversation."),
        ("Term Sheet Analyzer", "The real terms behind the headline valuation."),
        ("3-Year Revenue Projection", "The model investors will ask to see."),
        ("Scenario Model", "Downside / base / upside — asked in every diligence call."),
    ],
    "Finance shelf (available from Mission 8 onward)": [
        ("Income Statement (P&L)", "Monthly P&L once real numbers exist."),
        ("Cash Flow Statement", "Where cash actually moves."),
        ("Operating Budget / OpEx", "Departmental budget."),
        ("Working Capital", "Cash conversion cycle — critical for any inventory or services model."),
        ("Rolling Cash Forecast", "The 13-week view; the standard survival tool."),
        ("Break-Even Analysis", "When do revenues cover costs."),
        ("KPI Tracker — Actual vs Projected", "Plan vs reality, every month."),
    ],
    "Team & governance shelf (trigger: first hire, incorporation, contractor)": [
        ("Culture & Values", "Before the third person joins."),
        ("Team Structure & Equity", "Founder equity split — settle it early, in writing."),
        ("Team Roles & Hiring Plan", "Who to hire and when."),
        ("Hiring Cost Model", "Fully-loaded cost of a hire."),
        ("Compensation Bands", "Consistent pay before ad-hoc offers create problems."),
        ("Org Span of Control", "Org shape past ~8 people."),
        ("Legal Checklist", "Entity, founders' agreement, IP assignment, privacy."),
        ("IP Strategy", "Trademark and IP assignment."),
        ("Risk Register", "Standing register, reviewed monthly."),
        ("OKRs", "Quarterly goals once the team is more than the founders."),
        ("Vision & Mission", "Written once, referenced constantly."),
        ("Sales Velocity", "Once a pipeline exists."),
        ("Sales Capacity", "Once you have more than one seller."),
    ],
    "Scale shelf (post-Mission 15)": [
        ("Scaling Readiness Scorecard", "Are you ready to scale?"),
        ("Market Expansion Priority", "Which market next."),
        ("New Market Entry Scorecard", "Cross-border entry decision."),
        ("Partnership / BD Pipeline", "Partnerships as a growth channel."),
        ("Expansion & NRR", "Growth from existing accounts."),
        ("Revenue per Employee", "Productivity as you add headcount."),
        ("Rule of 40", "Growth-vs-profit balance."),
        ("Magic Number", "Sales efficiency."),
        ("Growth Accounting", "Decomposed growth."),
        ("Customer Health Score", "Retention early-warning system."),
        ("SaaS Metrics Dashboard", "The standing metrics board."),
        ("KPI Scorecard", "Target vs actual."),
        ("Growth Rate & CAGR", "Momentum."),
    ],
}
