"""
Startpad Tool Library — canonical inventory.

Source of truth: "Startpad — Tool Library (123 tools, Functional Categories).xlsx"
(121 tools in the workbook + 2 in the companion Word template = 123).

Each tool: (name, category, one_line, framework_reference, where_it_lives)
`where_it_lives` is the workbook tab (or DOCX) a founder opens to use the tool.
"""

# category -> sheet/tab the tool physically lives on
CATEGORY_TAB = {
    "Financial Statements": "Financial Statements",
    "Cap Table & Deal Terms": "Cap Table & Deal Terms",
    "KPI Tracker": "KPI Tracker",
    "Fundraising & Investor": "Fundraising & Investor",
    "Metrics & Growth Analytics": "Metrics & Growth Analytics",
    "Go-to-Market & Marketing": "Go-to-Market & Marketing",
    "Strategy & Business Model": "Strategy & Business Model",
    "Customer & Market Research": "Customer & Market Research",
    "Product & Build": "Product & Build",
    "Team & Operations": "Team & Operations",
    "Investor Materials (DOCX)": "Pitch Deck & One-Pager Template.docx",
}

# (name, category, what it does, framework reference)
TOOLS = [
    # ---------------- Financial Statements (10) ----------------
    ("Income Statement (P&L)", "Financial Statements",
     "Full monthly P&L with real expense breakdown", "GAAP-style income statement"),
    ("Cost Structure & Budget", "Financial Statements",
     "Full cost breakdown — COGS + OpEx by line item", "Zero-based budgeting"),
    ("Cash Flow Statement", "Financial Statements",
     "3-section monthly cash flow", "Indirect-method statement of cash flows"),
    ("3-Year Revenue Projection", "Financial Statements",
     "Annual, multi-stream revenue build", "Bottoms-up SaaS revenue build"),
    ("Burn Rate & Runway", "Financial Statements",
     "Monthly cash discipline tracker", "Startup burn-multiple & runway math"),
    ("Break-Even Analysis", "Financial Statements",
     "Unit economics of break-even", "Cost-volume-profit (CVP) analysis"),
    ("Scenario Model", "Financial Statements",
     "Downside / Base / Upside", "Scenario & sensitivity planning"),
    ("Operating Budget / OpEx", "Financial Statements",
     "Annual budget by department", "Departmental zero-based budget"),
    ("Working Capital", "Financial Statements",
     "Cash conversion cycle", "Working-capital & CCC analysis"),
    ("Rolling Cash Forecast", "Financial Statements",
     "The standard 13-week cash view", "13-week cash-flow forecast (CFO standard)"),

    # ---------------- Cap Table & Deal Terms (6) ----------------
    ("Cap Table — dynamic, multi-round", "Cap Table & Deal Terms",
     "Incorporation through each round, every holder's % auto-updates",
     "Standard priced-round cap table mechanics"),
    ("SAFE Conversion", "Cap Table & Deal Terms",
     "What your SAFE turns into when the next round happens", "YC post-money SAFE"),
    ("Quick Dilution What-If", "Cap Table & Deal Terms",
     "Fast napkin-math dilution check", "Priced-round dilution mechanics"),
    ("Use of Funds", "Cap Table & Deal Terms",
     "Where the raise goes", "Standard use-of-funds breakdown"),
    ("Funding Ask", "Cap Table & Deal Terms",
     "The one-line ask, backed by the math", "Fundraise sizing"),
    ("Term Sheet Analyzer", "Cap Table & Deal Terms",
     "Read the real terms, not just the headline valuation", "NVCA model term sheet"),

    # ---------------- KPI Tracker (1) ----------------
    ("KPI Tracker — Actual vs Projected", "KPI Tracker",
     "Fill actuals monthly; projected pulls live from the financial model",
     "Plan-vs-actual variance tracking"),

    # ---------------- Fundraising & Investor (5 unique) ----------------
    ("Pitch Narrative", "Fundraising & Investor",
     "The 7-beat story arc, in order", "Narrative arc for investor pitches"),
    ("Fundraising Pipeline", "Fundraising & Investor",
     "Your investor CRM", "Fundraising pipeline management"),
    ("Fundability Scorecard", "Fundraising & Investor",
     "Weighted investor-readiness score", "VC investment-criteria scoring"),
    ("Data Room Checklist", "Fundraising & Investor",
     "What investors will ask for in diligence", "VC due-diligence checklist"),
    ("Investor Update Delta", "Fundraising & Investor",
     "Month-over-month, ready to paste into your update",
     "Monthly investor-update format (YC / a16z style)"),

    # ---------------- Metrics & Growth Analytics (23) ----------------
    ("Unit Economics", "Metrics & Growth Analytics",
     "Per-unit profitability", "Unit economics / contribution margin"),
    ("SaaS Metrics Dashboard", "Metrics & Growth Analytics",
     "Core SaaS metrics in one view", "SaaS metrics (David Skok; Bessemer)"),
    ("LTV Calculator", "Metrics & Growth Analytics",
     "Lifetime value", "Customer Lifetime Value (LTV/CLV)"),
    ("MRR / ARR Tracker", "Metrics & Growth Analytics",
     "Track recurring revenue", "Recurring revenue (MRR/ARR)"),
    ("Cohort Retention", "Metrics & Growth Analytics",
     "Retention by signup cohort", "Cohort analysis"),
    ("Retention Curve", "Metrics & Growth Analytics",
     "See if retention flattens", "Retention cohorts / curve"),
    ("Magic Number", "Metrics & Growth Analytics",
     "Sales efficiency", "SaaS Magic Number (Scale VP)"),
    ("KPI Scorecard", "Metrics & Growth Analytics",
     "Track KPI vs target", "Balanced Scorecard (Kaplan & Norton)"),
    ("CAC Calculator", "Metrics & Growth Analytics",
     "Cost to acquire a customer", "Customer Acquisition Cost (CAC)"),
    ("LTV:CAC & Payback", "Metrics & Growth Analytics",
     "Efficiency of growth", "LTV:CAC & CAC payback (David Skok)"),
    ("Churn & Retention", "Metrics & Growth Analytics",
     "Measure stickiness", "Churn & retention rate"),
    ("Rule of 40", "Metrics & Growth Analytics",
     "Balance growth & profit", "Rule of 40 (Feld; Bessemer)"),
    ("Growth Rate & CAGR", "Metrics & Growth Analytics",
     "Quantify growth", "CAGR — Compound Annual Growth Rate"),
    ("North Star Metric", "Metrics & Growth Analytics",
     "One metric that matters", "North Star Metric (Amplitude; Sean Ellis)"),
    ("Growth Accounting", "Metrics & Growth Analytics",
     "Decompose net growth into new/resurrected/churned",
     "Growth accounting (Jonathan Hsu, Social Capital)"),
    ("DAU/MAU Stickiness", "Metrics & Growth Analytics",
     "Measure engagement frequency", "DAU/MAU stickiness ratio"),
    ("NPS", "Metrics & Growth Analytics",
     "Track customer love", "Net Promoter Score (Reichheld, Bain/HBR)"),
    ("Customer Health Score", "Metrics & Growth Analytics",
     "Predict retention", "Customer health score (Customer Success)"),
    ("Churn by Segment", "Metrics & Growth Analytics",
     "Find where churn concentrates", "Segmented churn analysis"),
    ("Engagement Score", "Metrics & Growth Analytics",
     "Quantify engagement", "Product-engagement scoring"),
    ("Feature Adoption", "Metrics & Growth Analytics",
     "Track feature uptake", "Feature-adoption rate"),
    ("Expansion & NRR", "Metrics & Growth Analytics",
     "Grow existing accounts", "Net Revenue Retention / expansion (Bessemer)"),
    ("Revenue per Employee", "Metrics & Growth Analytics",
     "Track productivity", "Revenue per employee (productivity)"),

    # ---------------- Go-to-Market & Marketing (21) ----------------
    ("Go-to-Market Plan", "Go-to-Market & Marketing",
     "Plan the route to market", "Go-to-market strategy"),
    ("Marketing Materials", "Go-to-Market & Marketing",
     "Plan launch assets", "Marketing collateral plan"),
    ("Launch Checklist", "Go-to-Market & Marketing",
     "Coordinate the launch", "Launch-readiness checklist"),
    ("Brand Identity", "Go-to-Market & Marketing",
     "Define the brand basics", "Brand Identity Prism (Kapferer)"),
    ("Channel CAC Planner", "Go-to-Market & Marketing",
     "Compare acquisition channels", "Customer Acquisition Cost (per channel)"),
    ("Content Cadence", "Go-to-Market & Marketing",
     "Plan content & cadence", "Content marketing calendar"),
    ("Marketing Strategy", "Go-to-Market & Marketing",
     "Plan marketing approach (STP + mix)", "STP & marketing mix / 4Ps (Kotler)"),
    ("PR Plan", "Go-to-Market & Marketing",
     "Plan press & outreach", "PR & communications plan"),
    ("Launch Event", "Go-to-Market & Marketing",
     "Plan a launch event", "Launch plan / event"),
    ("Landing Page Brief", "Go-to-Market & Marketing",
     "Spec the landing page", "Conversion-centred landing page (Wiebe)"),
    ("Marketing / Sales Funnel", "Go-to-Market & Marketing",
     "Model the conversion funnel", "AIDA / conversion funnel"),
    ("Launch Budget", "Go-to-Market & Marketing",
     "Budget the launch", "Launch budgeting / CPA"),
    ("Conversion Rate Optimisation", "Go-to-Market & Marketing",
     "Improve page conversion", "Conversion Rate Optimisation"),
    ("Paid Ads Performance", "Go-to-Market & Marketing",
     "Track ad efficiency", "Digital ad metrics (CTR/CPC/CPA)"),
    ("AARRR Funnel", "Go-to-Market & Marketing",
     "Measure the full funnel", "AARRR Pirate Metrics (Dave McClure)"),
    ("Channel ROI / ROAS", "Go-to-Market & Marketing",
     "Find profitable channels", "Return on Ad Spend (ROAS)"),
    ("A/B Test", "Go-to-Market & Marketing",
     "Test variants", "A/B / split testing (hypothesis testing)"),
    ("Referral / Viral Loop", "Go-to-Market & Marketing",
     "Build viral growth", "Viral coefficient / K-factor"),
    ("Experiment Backlog — ICE", "Go-to-Market & Marketing",
     "Prioritise growth bets", "ICE scoring (Sean Ellis, GrowthHackers)"),
    ("Experiment Tracker", "Go-to-Market & Marketing",
     "Run & log experiments", "Growth experimentation (Build-Measure-Learn)"),
    ("Pricing Tiering / ARPU", "Go-to-Market & Marketing",
     "Optimise pricing tiers", "Good-Better-Best tiering · ARPU"),

    # ---------------- Strategy & Business Model (17) ----------------
    ("Business Model Canvas", "Strategy & Business Model",
     "Map the whole model on one page", "Business Model Canvas (Osterwalder & Pigneur)"),
    ("Value Proposition Canvas", "Strategy & Business Model",
     "Fit value to customer", "Value Proposition Canvas (Osterwalder)"),
    ("PESTEL Analysis", "Strategy & Business Model",
     "Scan the macro environment", "PESTEL / PESTLE (Francis Aguilar)"),
    ("Competitor Feature Coverage", "Strategy & Business Model",
     "Map competitors & white space", "Competitive analysis / feature-gap matrix"),
    ("Elevator Pitch", "Strategy & Business Model",
     "Craft a 30-second pitch", "Elevator pitch / value positioning (Moore)"),
    ("Pricing Strategy", "Strategy & Business Model",
     "Set the right price", "Cost-plus & value-based pricing"),
    ("Positioning Statement", "Strategy & Business Model",
     "Own a clear position", "Positioning (Ries & Trout; Moore)"),
    ("Revenue Model Designer", "Strategy & Business Model",
     "Design how you earn", "Monetization / revenue-model patterns"),
    ("Vision & Mission", "Strategy & Business Model",
     "Set purpose & direction", "Vision/Mission (Collins & Porras)"),
    ("Lean Canvas", "Strategy & Business Model",
     "Lean one-page model", "Lean Canvas (Ash Maurya, Running Lean)"),
    ("SWOT Analysis", "Strategy & Business Model",
     "Internal/external position", "SWOT Analysis (Albert Humphrey, Stanford SRI)"),
    ("Porter's Five Forces", "Strategy & Business Model",
     "Assess industry attractiveness", "Five Forces (Michael Porter, HBR 1979)"),
    ("OKRs", "Strategy & Business Model",
     "Set measurable goals", "Objectives & Key Results (Grove; Doerr)"),
    ("Scaling Readiness Scorecard", "Strategy & Business Model",
     "Are you ready to scale?", "Scaling-readiness assessment"),
    ("Market Expansion Priority", "Strategy & Business Model",
     "Prioritise new markets", "Market prioritisation (TAM-based)"),
    ("New Market Entry Scorecard", "Strategy & Business Model",
     "Decide where to expand", "Market-entry analysis (CAGE / scoring)"),
    ("Partnership / BD Pipeline", "Strategy & Business Model",
     "Manage partnerships", "Weighted BD pipeline"),

    # ---------------- Customer & Market Research (16) ----------------
    ("Problem Statement", "Customer & Market Research",
     "Define the core problem precisely",
     "Lean Startup problem framing (Ries) · Design Thinking POV"),
    ("Market Sizing (TAM/SAM/SOM)", "Customer & Market Research",
     "Quantify the opportunity", "TAM / SAM / SOM market sizing"),
    ("Jobs-to-be-Done", "Customer & Market Research",
     "Capture the underlying job", "Jobs-to-be-Done Theory (Christensen; Ulwick)"),
    ("Idea Scorecard", "Customer & Market Research",
     "Score the opportunity objectively", "Weighted scoring / Pugh decision matrix"),
    ("Importance / Frequency Matrix", "Customer & Market Research",
     "Prioritise which problem to solve",
     "Opportunity scoring (Ulwick, Outcome-Driven Innovation)"),
    ("Customer Persona", "Customer & Market Research",
     "Define the target user", "Buyer/Proto-persona (Alan Cooper, About Face)"),
    ("Market Research Brief", "Customer & Market Research",
     "Understand market & trends", "Market & industry analysis"),
    ("Assumptions Tracker", "Customer & Market Research",
     "Rank riskiest assumptions",
     "Riskiest Assumption Test (Bland & Osterwalder, Testing Business Ideas)"),
    ("Interview Script Builder", "Customer & Market Research",
     "Design customer interviews",
     "The Mom Test (Fitzpatrick) · Customer Discovery (Blank)"),
    ("Survey Sample Size", "Customer & Market Research",
     "Quantify demand at scale", "Cochran's sample-size formula"),
    ("Willingness-to-Pay Test", "Customer & Market Research",
     "Find the acceptable price", "Van Westendorp Price Sensitivity Meter"),
    ("Waitlist / Pre-order Tracker", "Customer & Market Research",
     "Convert interest to commitment", "Pre-sell / concierge MVP validation"),
    ("Hypothesis Builder", "Customer & Market Research",
     "Turn assumptions into tests", "Build-Measure-Learn hypothesis (Ries)"),
    ("Interview Synthesis", "Customer & Market Research",
     "Extract signal from interviews", "Customer Discovery synthesis (Steve Blank)"),
    ("Demand / Smoke Test", "Customer & Market Research",
     "Measure real interest pre-build", "Smoke-test / landing-page MVP (Ries)"),
    ("Validation Scorecard", "Customer & Market Research",
     "Single evidence-based score", "Evidence-based validation (Testing Business Ideas)"),

    # ---------------- Product & Build (9) ----------------
    ("MVP Scope (MoSCoW)", "Product & Build",
     "Define the smallest valuable build", "MoSCoW prioritisation (DSDM) · MVP (Ries)"),
    ("Feature Prioritisation — RICE", "Product & Build",
     "Rank features by impact", "RICE scoring (Intercom)"),
    ("Product Roadmap", "Product & Build",
     "Sequence what you build", "Now-Next-Later roadmap (Janna Bastow)"),
    ("Tech Stack Selector", "Product & Build",
     "Choose the stack", "Weighted decision matrix"),
    ("User Testing Synthesis", "Product & Build",
     "Learn from prototype tests", "Usability testing (Nielsen) · SUS (Brooke)"),
    ("Product Description", "Product & Build",
     "Describe the product clearly", "Product positioning / one-liner"),
    ("Value vs Effort", "Product & Build",
     "Quick prioritisation", "Value/Effort (Impact-Effort) matrix"),
    ("Sprint Velocity / ETA", "Product & Build",
     "Plan the build sprints", "Agile velocity (Scrum)"),
    ("Build vs Buy", "Product & Build",
     "Decide build or integrate", "Build-vs-Buy / Total Cost of Ownership"),

    # ---------------- Team & Operations (12) ----------------
    ("Culture & Values", "Team & Operations",
     "Define values & ways of working", "Core values & culture (Lencioni)"),
    ("Risk Register", "Team & Operations",
     "Identify & rank risks", "Risk register / Probability-Impact matrix (PMI PMBOK)"),
    ("Team Roles & Hiring Plan", "Team & Operations",
     "Plan roles to hire & when", "Organisational design & hiring plan"),
    ("Legal Checklist", "Team & Operations",
     "Cover legal basics", "Startup legal & compliance checklist"),
    ("IP Strategy", "Team & Operations",
     "Protect intellectual property", "Intellectual-property strategy"),
    ("Team Structure & Equity", "Team & Operations",
     "Map founders, roles & equity", "Founder equity split (Slicing Pie, Mike Moyer)"),
    ("Hiring Cost Model", "Team & Operations",
     "Plan & cost hiring", "Fully-loaded labour cost"),
    ("Org Span of Control", "Team & Operations",
     "Design the org", "Span of control (org design)"),
    ("Compensation Bands", "Team & Operations",
     "Standardise pay", "Compensation banding / compa-ratio"),
    ("Sales Velocity", "Team & Operations",
     "Speed up the pipeline", "Sales velocity formula"),
    ("Sales Strategy", "Team & Operations",
     "Plan the sales motion", "Sales methodology (SPIN / Challenger / MEDDIC)"),
    ("Sales Capacity", "Team & Operations",
     "Plan sales capacity", "Sales capacity planning"),

    # ---------------- Investor Materials — companion DOCX (2) ----------------
    ("Pitch Deck Builder (12 slides)", "Investor Materials (DOCX)",
     "The 12-slide deck outline, one page per slide", "Sequoia / YC deck structure"),
    ("Investor One-Pager", "Investor Materials (DOCX)",
     "One page you can send cold or leave behind", "Investor one-pager / teaser"),
]

TOOL_BY_NAME = {t[0]: t for t in TOOLS}
CATEGORY_ORDER = [
    "Customer & Market Research",
    "Strategy & Business Model",
    "Product & Build",
    "Go-to-Market & Marketing",
    "Metrics & Growth Analytics",
    "Financial Statements",
    "KPI Tracker",
    "Cap Table & Deal Terms",
    "Fundraising & Investor",
    "Investor Materials (DOCX)",
    "Team & Operations",
]
