"""
Verify the resource library.

Checks each PDF against the things that would make it wrong in a way a page count
would not reveal: missing brand furniture, an AI or browser fingerprint left in the
metadata, a figure that rendered as nothing, a document with no closing page, and
any of the phrases the brand voice rules forbid.

    python3 scripts/check_pdfs.py
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pypdf import PdfReader                        # noqa: E402

from whitepapers import brand as B                 # noqa: E402
from whitepapers.library import LIBRARY            # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "output", "resources")

# Anything that would tell a reader the file came out of a machine rather than out
# of StartPad. These documents are published under the company's name.
FINGERPRINTS = ["claude", "anthropic", "chromium", "skia", "chrome", "headless",
                "generated by", "ai-generated", "playwright", "wkhtmltopdf",
                "language model"]


def check(doc):
    path = os.path.join(OUT, f"{doc['file']}.pdf")
    problems = []
    if not os.path.exists(path):
        return [f"missing file: {doc['file']}.pdf"], 0

    reader = PdfReader(path)
    pages = len(reader.pages)
    text = "\n".join((p.extract_text() or "") for p in reader.pages)
    low = text.lower()

    meta = {str(k): str(v) for k, v in (reader.metadata or {}).items()}
    meta_blob = " ".join(meta.values()).lower()

    for mark in FINGERPRINTS:
        if mark in meta_blob:
            problems.append(f"metadata fingerprint: {mark!r} in {meta}")
        if mark in low:
            problems.append(f"body fingerprint: {mark!r}")

    if meta.get("/Author") != "StartPad":
        problems.append(f"author is {meta.get('/Author')!r}, expected 'StartPad'")
    if meta.get("/Producer") != "StartPad":
        problems.append(f"producer is {meta.get('/Producer')!r}, expected 'StartPad'")
    if meta.get("/Title") != doc["title"]:
        problems.append("title metadata does not match the document title")

    # Content checks run against the lowercased text: the cover series line and the
    # section labels are uppercased by the stylesheet, so they never match their
    # mixed-case source.
    if B.URL not in low:
        problems.append("startpad.me does not appear in the text")
    if "founder-readiness platform" not in low or "we just kept the file" in low[:200]:
        problems.append("closing About StartPad page is missing")
    if doc["series"].lower() not in low:
        problems.append("cover series line is missing")
    if doc["title"].lower() not in low:
        problems.append("cover title is missing")

    # Every figure must have reached the page: count the captions, which only exist
    # where a figure rendered.
    figs = sum(1 for b in doc["blocks"] if b[0] == "fig")
    fonts = set()
    for p in reader.pages:
        fonts |= set((p.get("/Resources", {}) or {}).get("/Font", {}) or {})
    if figs and not fonts:
        problems.append("no embedded fonts found")

    # Voice rules: the brand lists these as never-say.
    for phrase in B.NEVER_SAY:
        # they are legitimate inside the SAY / NEVER SAY table, which prints both
        # columns on purpose, so only flag documents that have no such table
        has_table = any(b[0] == "say" for b in doc["blocks"])
        if phrase.lower() in low and not has_table:
            problems.append(f"forbidden phrase in copy: {phrase!r}")

    if pages < 5:
        problems.append(f"only {pages} pages")

    # The ordinal ramp separates at most six steps. Past that, two adjacent items
    # in a funnel, ladder, flow or timeline stop being distinguishable, so the
    # ceiling is checked here rather than trusted.
    from whitepapers import figures as FIG
    counted = {"funnel": "stages", "ladder": "rungs", "flow": "steps",
               "timeline": "phases", "nested": "layers", "stack": "segments",
               "bands": "segments"}
    for b in doc["blocks"]:
        if b[0] != "fig" or b[1] not in counted:
            continue
        items = len(b[2][counted[b[1]]])
        if items > FIG.MAX_ORDINAL_STEPS:
            problems.append(
                f"{b[1]} figure has {items} ordinal steps, "
                f"above the ramp's ceiling of {FIG.MAX_ORDINAL_STEPS}")

    return problems, pages


def main():
    total_pages = 0
    failed = 0
    print(f"{'document':<56}{'pages':>6}   result")
    print("-" * 78)
    for doc in LIBRARY:
        problems, pages = check(doc)
        total_pages += pages
        status = "ok" if not problems else f"{len(problems)} problem(s)"
        print(f"{doc['file']:<56}{pages:>6}   {status}")
        for p in problems:
            print(f"        - {p}")
        failed += bool(problems)
    print("-" * 78)
    print(f"{len(LIBRARY)} documents, {total_pages} pages, {failed} with problems")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
